Repository PsiFacilita/sistema-web, pull requests merged in 2025-04, with the labels that each got.

#11 docs: atualizando o README com a documentação sobre comandos Docker
  README.md
Labels: docs

#20 chore/atualizando versão da imagem node
  README.md
  backend/Dockerfile
  frontend/Dockerfile
Labels: chore

#14 style/instalando tailwind
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/tailwind.config.js
Labels: chore, style

#26 feat/desenvolvendo-componente-ancora
  frontend/src/App.tsx
  frontend/src/components/Anchor.tsx
  frontend/src/components/Anchor.types.ts
  frontend/src/pages/AnchorPage.tsx
Labels: feat

#18 feat/desenvolvendo componente de modal de alerta
  frontend/src/components/AlertModal/AlertModal.tsx
  frontend/src/components/AlertModal/AlertModal.types.tsx
  frontend/src/components/AlertModal/AlertModalIcons.tsx
  frontend/src/components/AlertModal/AlertModalStyles.module.css
  frontend/src/components/AlertModal/hooks/useModalAnimation.ts
  frontend/src/components/AlertModal/hooks/useModalAnimation.types.ts
  frontend/src/pages/LoginPage.tsx
Labels: feat

#27 Implementação do componente List
  frontend/src/components/List/List.css
  frontend/src/components/List/List.test.tsx
  frontend/src/components/List/List.tsx
  frontend/src/components/List/List.types.tsx
  frontend/src/pages/ListPage.tsx
Labels: feat

#25 feat/criando componente de dropdown
  frontend/src/components/Dropdown/Dropdown.css
  frontend/src/components/Dropdown/Dropdown.tsx
  frontend/src/components/Dropdown/Dropdown.types.tsx
  frontend/src/pages/TestDropdownPage.tsx
Labels: feat

#19 feat/criando banco de dados
  database/PsiFacilita_tables.sql
Labels: feat

#41 Feature/desenvolvendo componente icon
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Icon/Icon.tsx
  frontend/src/components/Icon/Icon.types.tsx
Labels: feat

#33 Feature/desenvolvendo componente botao
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/Button.types.tsx
  frontend/src/components/Button/index.ts
Labels: feat

#35 Feature/desenvolvendo componente chart
  frontend/src/components/Chart/Chart.tsx
  frontend/src/components/Chart/index.ts
Labels: feat

#43 Feature/desenvolvendo componente title
  frontend/src/components/Title/Title.tsx
Labels: feat

#37 Desenvolvendo componente DocumentCategoryDropdown com categorias expa…
  frontend/src/components/DocumentCategoryDropdown/DocumentCategoryDropdown.tsx
  frontend/src/components/DocumentCategoryDropdown/index.ts
Labels: feat

#38 Feature/desenvolvendo componente form
  frontend/src/components/Form/Input/Input.tsx
  frontend/src/components/Form/Input/index.ts
  frontend/src/components/Form/Label/Label.tsx
  frontend/src/components/Form/Label/index.ts
  frontend/src/components/Form/Select/Select.tsx
  frontend/src/components/Form/Select/index.ts
Labels: feat

#39 Feature/desenvolvendo componente personal data settings
  frontend/src/components/PersonalDataSettings/PersonalDataSettings.tsx
  frontend/src/components/PersonalDataSettings/index.ts
Labels: feat

#48 Feature/adicionando tela playground
  frontend/src/pages/Playground.tsx
Labels: feat

#47 Feature/adicionando tela configurações
  frontend/src/pages/Settings/index.tsx
Labels: feat

#44 Feature/desenvolvendo componente workschedulemanager
  frontend/src/components/WorkScheduleManager/WorkScheduleManager.tsx
Labels: feat

#46 Feature/adicionando tela dashboard
  frontend/src/pages/Dashboard/index.tsx
Labels: feat

#42 Desenvolvimento de componente de tabela com suporte a colunas customizadas
  frontend/src/components/Table/Table.tsx
Labels: feat

#49 Feature/desenvolvendo componente modal
  frontend/src/components/Modal/Modal.tsx
Labels: feat

#51 Atualizando tailwind com cores personalizadas
  frontend/tailwind.config.js
Labels: chore
